#!/bin/sh

# i will be the active, currently focused monitor
# j will be the monitor with the desired workspace
for i in $(hyprctl -j monitors | jq '.[].id'); do
	if $(hyprctl -j monitors | jq '.['$i'].active'); then
		hyprctl dispatch workspace $1 # change to desired workspace to check for active
		for j in $(hyprctl -j monitors | jq '.[].id'); do
			if $(hyprctl -j monitors | jq '.['$j'].active'); then
				break # find monitor with desired workspace
			fi
		done
		hyprctl dispatch focusmonitor $i # focus back first monitor
		hyprctl dispatch movecurrentworkspacetomonitor $j # move initial workspace to second monitor
		hyprctl dispatch workspace $1 # focus desired workspace
		hyprctl dispatch movecurrentworkspacetomonitor $i # move desired workspace to first monitor
		break
	fi
done



