#!/bin/sh

mon=$(hyprctl -j monitors)
for i in $(printf "$mon" | jq '.[].id'); do
  if $(printf "$mon" | jq ".[$i].focused"); then
    active=$i
  fi
done

hyprctl dispatch workspace name:$1
mon=$(hyprctl -j monitors)
for i in $(printf "$mon" | jq '.[].id'); do
  if $(printf "$mon" | jq ".[$i].focused"); then
    hasWs=$i
  fi
done

hyprctl dispatch focusmonitor $hasWs
hyprctl dispatch swapactiveworkspaces $active $hasWs
hyprctl dispatch focusmonitor $active
sleep 0.2
hyprctl dispatch movecursortocorner 3
